### PR TITLE
1.3 reporter

### PR DESCRIPTION
**Pull request by tmeasday**
Hey @rbabayoff -- here is the PR for the pm:mocha package.

Feel free to squash the commits / change version numbers etc.

It probably makes sense to release this as a `.beta` release for now so non-1.3 users don't get it.

### CODE REVIEW

**Comment by rbabayoff** [comment]
@tmeasday any chance to resolve the merge conflicts?

**Comment by tmeasday** [comment]
Ok I've resolved the conflicts.

Please note that there is an issue with beta.16 that will stop this package working so I'd suggest publishing a version against beta.12 and then (maybe) another version against the next beta (let's say beta.17, although it may be a different number)

**Comment by rbabayoff** [comment]
@tmeasday this doesn't work with test-packages. Any clues into possibly why?

**Comment by rbabayoff** [comment]
@tmeasday you can't also import practicalmeteor:mocha when running meteor test-packages but when running meteor test, you can.

**Comment by rbabayoff** [comment]
@tmeasday not only this pr, this package doesn't work anymore with 1.3. Did anything change with test-packages in meteor that you know of?

**Comment by rbabayoff** [comment]
@tmeasday found it - testOnly in package.js. Removing it makes it work with test-packages, i.e. meteor finds practicalmeteor:mocha. But, there is a problem with your package, test-reporter-helpers is missing a dependency on underscore. Should I create a pr or are you on it? Here are steps to reproduce (remove testOnly first):

```
cd mocha
export PPACKAGE_DIRS=$PWD
cd meteor/test-package
meteor --release 1.3-beta.12 test-packages --driver-package=practicalmeteor:mocha ./
```

We also created a test-app in [this](https://github.com/practicalmeteor/meteor-mocha/tree/meteor1.3) branch that includes your pr, so you can check it still works with `meteor test`

**Comment by tmeasday** [comment]
Yup, fixed in `tmeasday:test-reporter-helpers@0.2.1`

**Comment by tmeasday** [comment]
(See other comments about `testOnly` and `test-packages`)

**Comment by rbabayoff** [comment]
@tmeasday so we remove testOnly, for now, until you guys decide how you want to handle the testOnly flag with driver packages.

**Comment by tmeasday** [comment]
Ok, it shouldn't be necessary in the next release: https://github.com/meteor/meteor/pull/6479/files

**Comment by jsep** [comment]
We tested with your that merge and it working as expected

**Pull request merged**
